module OrientdbBinary
  module OperationTypes
    NEW_SESSION = -1
    REQUEST_SHUTDOWN = 1
    REQUEST_CONNECT = 2
    REQUEST_DB_OPEN = 3
    REQUEST_DB_CREATE =4
    REQUEST_DB_CLOSE = 5
    REQUEST_DB_EXIST = 6
    REQUEST_DB_DROP = 7
    REQUEST_RECORD_LOAD = 30
    REQUEST_COMMAND = 41
    REQUEST_CONFIG_GET = 70
    REQUEST_CONFIG_SET = 71
    REQUEST_CONFIG_LIST = 72
    REQUEST_DB_RELOAD = 73
  end
end
